name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lab2Test
      id: lab2test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lab2Test
        setup-command: ''
        command: mvn test
        timeout: 5
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB2TEST_RESULTS: "${{steps.lab2test.outputs.result}}"
      with:
        runners: lab2test
